[package]
name = "crypto-streams"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
hmac = "0.12.1"
sha2 = "0.10.8"
